/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/calculator.gltf')
  const { actions } = useAnimations(animations, group)
  console.log(actions)



  return (
    <group ref={group} {...props} dispose={null} position={[0,0,0]}>
      <group name="Scene">
        <group name="Cube" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials.calculatorBody} />
          <mesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials.text} />
        </group>
        <group name="Cube001" position={[0,0,0]} scale={[0.52, 0.96, 0.12]} 
                onClick={(() => {
                  console.log("ON/C pushed!")
                  actions.onOffButton.play()
                })}>
          <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials.onOffButton} />
          <mesh name="Cube001_2" geometry={nodes.Cube001_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube002" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials.Material} />
          <mesh name="Cube002_2" geometry={nodes.Cube002_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube003" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube003_1" geometry={nodes.Cube003_1.geometry} material={materials.Material} />
          <mesh name="Cube003_2" geometry={nodes.Cube003_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube004" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube004_1" geometry={nodes.Cube004_1.geometry} material={materials.Material} />
          <mesh name="Cube004_2" geometry={nodes.Cube004_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube005" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube005_1" geometry={nodes.Cube005_1.geometry} material={materials.Material} />
          <mesh name="Cube005_2" geometry={nodes.Cube005_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube006" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube006_1" geometry={nodes.Cube006_1.geometry} material={materials.Material} />
          <mesh name="Cube006_2" geometry={nodes.Cube006_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube007" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube007_1" geometry={nodes.Cube007_1.geometry} material={materials.Material} />
          <mesh name="Cube007_2" geometry={nodes.Cube007_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube008" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube008_1" geometry={nodes.Cube008_1.geometry} material={materials.Material} />
          <mesh name="Cube008_2" geometry={nodes.Cube008_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube009" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube009_1" geometry={nodes.Cube009_1.geometry} material={materials.Material} />
          <mesh name="Cube009_2" geometry={nodes.Cube009_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube010" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube010_1" geometry={nodes.Cube010_1.geometry} material={materials.Material} />
          <mesh name="Cube010_2" geometry={nodes.Cube010_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube011" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube011_1" geometry={nodes.Cube011_1.geometry} material={materials.Material} />
          <mesh name="Cube011_2" geometry={nodes.Cube011_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube012" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube012_1" geometry={nodes.Cube012_1.geometry} material={materials.Material} />
          <mesh name="Cube012_2" geometry={nodes.Cube012_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube013" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube013_1" geometry={nodes.Cube013_1.geometry} material={materials.Material} />
          <mesh name="Cube013_2" geometry={nodes.Cube013_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube014" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube014_1" geometry={nodes.Cube014_1.geometry} material={materials.Material} />
          <mesh name="Cube014_2" geometry={nodes.Cube014_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube015" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube015_1" geometry={nodes.Cube015_1.geometry} material={materials.Material} />
          <mesh name="Cube015_2" geometry={nodes.Cube015_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube016" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube016_1" geometry={nodes.Cube016_1.geometry} material={materials.Material} />
          <mesh name="Cube016_2" geometry={nodes.Cube016_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube017" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube017_1" geometry={nodes.Cube017_1.geometry} material={materials.Material} />
          <mesh name="Cube017_2" geometry={nodes.Cube017_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube018" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube018_1" geometry={nodes.Cube018_1.geometry} material={materials.Material} />
          <mesh name="Cube018_2" geometry={nodes.Cube018_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube019" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube019_1" geometry={nodes.Cube019_1.geometry} material={materials.Material} />
          <mesh name="Cube019_2" geometry={nodes.Cube019_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube020" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube020_1" geometry={nodes.Cube020_1.geometry} material={materials.Material} />
          <mesh name="Cube020_2" geometry={nodes.Cube020_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube021" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube021_1" geometry={nodes.Cube021_1.geometry} material={materials.Material} />
          <mesh name="Cube021_2" geometry={nodes.Cube021_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube022" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube022_1" geometry={nodes.Cube022_1.geometry} material={materials.Material} />
          <mesh name="Cube022_2" geometry={nodes.Cube022_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube023" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube023_1" geometry={nodes.Cube023_1.geometry} material={materials.Material} />
          <mesh name="Cube023_2" geometry={nodes.Cube023_2.geometry} material={materials.buttonText} />
        </group>
        <group name="Cube024" position={[0,0,0]} scale={[0.52, 0.96, 0.12]}>
          <mesh name="Cube024_1" geometry={nodes.Cube024_1.geometry} material={materials.Material} />
          <mesh name="Cube024_2" geometry={nodes.Cube024_2.geometry} material={materials.buttonText} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/calculator.gltf')
